### PR TITLE
Included option.

### PR DESCRIPTION
**Pull request by SeyZ**

### CODE REVIEW

**Comment by SeyZ** [comment]
@m-bodmer @digia

Here's a pull request about the issue #6 
What do you think about my implementation?

**Comment by m-bodmer** [comment]
I like it! :+1: Just missing README explanation / comments

**Comment by SeyZ** [comment]
Right. I'm gonna update the README

**Comment by SeyZ** [comment]
@digia Do you agree with the new option `included`?

**Comment by digia** [comment]
@SeyZ Just did a quick scan - in middle of project - but it looked good from what i saw.

**Pull request merged**
