### PR TITLE
JSON API errors support

### PR DESCRIPTION
**Pull request by ozanmuyes**
- Basic error support via  
`return next(new JSONAPIError({ id: '1', status: 415 }));`,
`return next(new JSONAPIError(415, '', '', '1'));`,
`return next(NotFound({ code: '0xABBA', status: '404' }));`, or
`return next(NotFound('', '0xABBA'));`
- Automatically set the 'title' property in order to sustain compliancy.
- No support for multiple errors (yet).
- Error handler middleware to wrap things up and do a final touch.
- Tests are written, can be populated upon request.

Any thoughts?

### CODE REVIEW

**Comment by SeyZ** [comment]
Thanks for boostraping the feature @ozanmuyes !

**Comment by ozanmuyes** [comment]
You are welcome @SeyZ and hope this eases the errors feature for future users. Hopefully it closes #121.

**Comment by SeyZ** [comment]
Hey @ozanmuyes 

I've implemented the support of errors in the PR #131 - highly inspired from this PR. JSONAPI specifiies that an error must contain the `errors: []` array:

`Error objects MUST be returned as an array keyed by errors in the top level of a JSON API document.`

I think my PR is more simple and support multiple errors.

Thank you one more time for your job!

**Comment by ozanmuyes** [comment]
Bummer, I missed that "error must contain the `errors: []` array". I am happy to contribute to this library somehow. Keep up the good work @SeyZ, thanks!

**Pull request closed without merging**
