### PR TITLE
replace bluebird usage with native Promise

### PR DESCRIPTION
**Pull request by hartzis**
remove `bluebird` dep - #123

### CODE REVIEW

**Comment by hartzis** [comment]
- [ ] update pr to include documentation related to performance related to `bluebird` and polyfill options, per [123 recommendation](https://github.com/SeyZ/jsonapi-serializer/issues/123#issuecomment-278507991)

**Comment by hartzis** [comment]
also added a test for `valueForRelationship` returning a promise since that is the main reason for promises in the package :)

**Comment by CacheControl** [comment]
@SeyZ Any feedback?  Would be nice to get this merged.

**Comment by SeyZ** [comment]
Hey @hartzis thank you so much for the PR and all your kind words!
@CacheControl sure! sorry for delay :)

**Comment by CacheControl** [comment]
nice!  thanks for the quick response @SeyZ

**Pull request merged**
