### PR TITLE
Reused nested relationships

### PR DESCRIPTION
**Pull request by pokiujf**
These are the tests showing problem from the issue #141

### CODE REVIEW

**Comment by Skysplit** [comment]
@SeyZ this PR should fix the problem. One test case had to be modified because there was no possibility to completely remove circular dependency. At the moment it adds one redundant level, but I think that's fine.

**Comment by heavysixer** [comment]
I just hit this bug myself and noticed that many of these PRs for this lib are nearly a year old. Is there an active fork for this project or is the main trunk still active?

**Comment by SeyZ** [comment]
Shit, my bad @heavysixer ;-) I will try to check the test case to reproduce the bug and see if this PR is up to date. Sorry!

**Comment by heavysixer** [comment]
@SeyZ thanks so much!

**Pull request merged**
