### PR TITLE
Add meta to the data object

### PR DESCRIPTION
**Pull request by dakolech**
It should be meta object in data after deserialization. It may contain some important data.

### CODE REVIEW

**Comment by SeyZ** [comment]
Hey @dakolech you're right! Can you add a unit test for your improvement to keep having ~100% test coverage :) ?

**Comment by dakolech** [comment]
Updated :) I also used keyForAttribute method.

**Comment by darioghilardi** [comment]
Hey @SeyZ,
can we merge this PR?
In case something is missing I might be able to help, let me know :-)

**Comment by SeyZ** [comment]
Hey @darioghilardi @dakolech It's now merged! Sorry for delay guys !

**Pull request merged**
