### PR TITLE
[fix] RFC: JSON API deserialize

### PR DESCRIPTION
**Pull request by sescobb27**
[add] add support for deserialization

### CODE REVIEW

**Comment by buritica** [comment]
👍

**Comment by SeyZ** [comment]
@sescobb27 and @buritica 

I'm working on the deserializer part: https://github.com/SeyZ/jsonapi-serializer/tree/deserializer
I think I have a different approach :)

Thoughts? Your opinions matter a lot to me :)

**Comment by sescobb27** [comment]
@SeyZ I see what you are doing, you are trying to make it accessible form browser and backend at the same time, I forgot about JSON API's `included` part. My thoughts are, why did you introduce bluebird? I think you are over-engineering the API, also you aren't following serializer's API making things more complicated to understand and implement. 
I thing you can gain more performance and compatibility with plain callbacks or returning JS Objects https://github.com/petkaantonov/bluebird/tree/master/benchmark and let user's choose which approach to use (RSVP, Q, Bluebird, Callbacks, JQuery Promises etc)
@buritica what do you think?

**Comment by buritica** [comment]
I think I see @sescobb27's point on the flow control option, but I don't consider it over-engineering. I think it's probably harder to provide a good way for people to choose the way they want to consume flow control. 

For this, probably the best way is to leave regular callbacks, and allow people to nodeify or you could expose a promisifed version. Ultimately, I have no strong opinion, I think it works as intended and I don't mind consuming promises.

**Comment by iamsebastian** [comment]
I also think, it's the right way to let the user decide, how to handle the callbacks.
You are fine, if you go on with regular callbacks. It's the "standard" in node - also for performance.

**Comment by listepo** [comment]
What progress?

**Comment by Aurelsicoko** [comment]
+1

I really need this improvement!

**Comment by sescobb27** [comment]
Right now, in the company I work at, we are working with my own fork https://github.com/sescobb27/jsonapi-serializer I already implement this RFC and made a PR but it hasn't  been accepted, you can check it if you want

**Comment by Aurelsicoko** [comment]
@sescobb27: Thanks for sharing! I was thinking to fork this beautiful library too but I don't want to...

**Comment by SeyZ** [comment]
The new deserializer of this library will be released soon. Work in progress on the https://github.com/SeyZ/jsonapi-serializer/tree/deserializer branch :+1:

**Comment by Aurelsicoko** [comment]
@SeyZ: How long will it take before the release?

**Comment by SeyZ** [comment]
@Aurelsicoko I will work on it this weekend. Sorry for delay :)

**Comment by Aurelsicoko** [comment]
@SeyZ: Awesome! Your library is really cool and easy to use :)

**Comment by SeyZ** [comment]
@Aurelsicoko @sescobb27  I have merged my deserializer on the master :)

**Comment by Aurelsicoko** [comment]
Awesome! Thanks a lot :)

**Pull request closed without merging**
