### PR TITLE
Ensure pluralizeType boolean works for included resources

### PR DESCRIPTION
**Pull request by estefaniaa**

### CODE REVIEW

**Comment by SeyZ** [comment]
Hi @estefaniaa ! Thanks for your PR.

Instead of introducing a new attribute `resourceType`, I see two other options. Your opinion will be very helpful:

* Use the

**Comment by estefaniaa** [comment]
Ahh. I missed the `typeForAttribute` option! I had an older version of the serializer.

I was a bit confused as to why you would want some types to be pluralized and not others, but I recognize there may be a need to customize each resource instead of applying a rule across the board. 

The way we are using it, we are applying the rule to all resources types via middleware, e.g. 

```
app.use(routes, function(req, res, next) {
	// Serialize API response to JSON api standards
	var JSONAPISettings = res.locals.JSONAPISerializerConfig,
		status = res.locals.status || 200;

	if (JSONAPISettings) {
		// Ensure all types are singular
		JSONAPISettings.pluralizeType = false;
		JSONAPISettings.typeForAttribute = function(attribute) {
			return inflection.singularize(attribute);
		};
		// Set option to output fields as camelCase
		JSONAPISettings.keyForAttribute = function (attribute) {
			return inflection.camelize(attribute, true);
		};
		new JSONAPISerializer(JSONAPISettings.resourceType, res.body, JSONAPISettings)
			.then(function(serializedData) {
				res.status(status).json(serializedData);
			});
	} else { ... }
});
```

Thanks!

**Comment by SeyZ** [comment]
Excellent! I like your express middleware idea!

**Comment by estefaniaa** [comment]
@SeyZ Thank @m-bodmer, it was his implementation ;)

**Pull request closed without merging**
